//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UABEANext4.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UABEANext4.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Info.
        /// </summary>
        public static string Asset_Info {
            get {
                return ResourceManager.GetString("Asset Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        public static string Close_All {
            get {
                return ResourceManager.GetString("Close All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Tab.
        /// </summary>
        public static string Duplicate_Tab {
            get {
                return ResourceManager.GetString("Duplicate Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data.
        /// </summary>
        public static string Edit_Data {
            get {
                return ResourceManager.GetString("Edit Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        public static string Hierarchy {
            get {
                return ResourceManager.GetString("Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort root GameObjects alphabetically.
        /// </summary>
        public static string Hierarchy_GameObject_Sort {
            get {
                return ResourceManager.GetString("Hierarchy GameObject Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        public static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All.
        /// </summary>
        public static string Load_All {
            get {
                return ResourceManager.GetString("Load All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string New_Tab {
            get {
                return ResourceManager.GetString("New Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an assets file or bundle file and select it in the Workspace Explorer to load it here..
        /// </summary>
        public static string New_Tab_Prompt {
            get {
                return ResourceManager.GetString("New Tab Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview available..
        /// </summary>
        public static string No_Preview_Available {
            get {
                return ResourceManager.GetString("No Preview Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file.
        /// </summary>
        public static string Open_A_File {
            get {
                return ResourceManager.GetString("Open A File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a folder.
        /// </summary>
        public static string Open_A_Folder {
            get {
                return ResourceManager.GetString("Open A Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Open_Folder {
            get {
                return ResourceManager.GetString("Open Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previewer.
        /// </summary>
        public static string Previewer {
            get {
                return ResourceManager.GetString("Previewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string Save_All {
            get {
                return ResourceManager.GetString("Save All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected.
        /// </summary>
        public static string Save_Selected {
            get {
                return ResourceManager.GetString("Save Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected As....
        /// </summary>
        public static string Save_Selected_As {
            get {
                return ResourceManager.GetString("Save Selected As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Bytes {
            get {
                return ResourceManager.GetString("Search Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes in this dialog save immediately..
        /// </summary>
        public static string Settings_Prompt {
            get {
                return ResourceManager.GetString("Settings Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Type.
        /// </summary>
        public static string Theme_Type {
            get {
                return ResourceManager.GetString("Theme Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme to use..
        /// </summary>
        public static string Theme_Type_Description {
            get {
                return ResourceManager.GetString("Theme Type Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Scene.
        /// </summary>
        public static string View_Scene {
            get {
                return ResourceManager.GetString("View Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Explorer.
        /// </summary>
        public static string Workspace_Explorer {
            get {
                return ResourceManager.GetString("Workspace Explorer", resourceCulture);
            }
        }
    }
}
